<html xmlns:string="xalan://java.lang.String" xmlns:lxslt="http://xml.apache.org/xslt">
<head>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Unit Test Results: All Errors</title>
<link rel="stylesheet" type="text/css" title="Style" href="stylesheet.css">
</head>
<body onload="open('allclasses-frame.html','classListFrame')">
<h1>Unit Test Results.</h1>
<table width="100%">
<tr>
<td align="left"></td><td align="right">Designed for use with <a href="http://www.junit.org/">JUnit</a> and <a href="http://ant.apache.org/">Ant</a>.</td>
</tr>
</table>
<hr size="1">
<h2>All Errors</h2>
<table class="details" border="0" cellpadding="5" cellspacing="2" width="95%">
<tr valign="top">
<th>Class</th><th>Name</th><th>Status</th><th width="80%">Type</th><th nowrap>Time(s)</th>
</tr>
<tr valign="top" class="Error">
<td><a href="info/jtrac/0_JtracTest.html">JtracTest</a></td><td><a name="testDefaultAdminUserHasAdminRole"></a><a href="info/jtrac/0_JtracTest.html#testDefaultAdminUserHasAdminRole">testDefaultAdminUserHasAdminRole</a></td><td>Error</td><td>User not found for 'admin'<br>
<br>
<code>org.acegisecurity.userdetails.UsernameNotFoundException: User not found for 'admin'<br>	at info.jtrac.JtracImpl.loadUserByUsername(JtracImpl.java:428)<br>	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:301)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)<br>	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)<br>	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)<br>	at com.sun.proxy.$Proxy1.loadUserByUsername(Unknown Source)<br>	at info.jtrac.JtracTest.testDefaultAdminUserHasAdminRole(JtracTest.java:156)<br>	at org.springframework.test.ConditionalTestCase.runBare(ConditionalTestCase.java:76)<br>
</code></td><td>3.119</td>
</tr>
<tr valign="top" class="Error">
<td><a href="info/jtrac/0_JtracTest.html">JtracTest</a></td><td><a name="testLogicToFindNotUsersAndSpacesNotAllocated"></a><a href="info/jtrac/0_JtracTest.html#testLogicToFindNotUsersAndSpacesNotAllocated">testLogicToFindNotUsersAndSpacesNotAllocated</a></td><td>Error</td><td>could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>
<br>
<code>org.springframework.dao.DataIntegrityViolationException: could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:622)<br>	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:378)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.merge(HibernateTemplate.java:769)<br>	at info.jtrac.hibernate.HibernateJtracDao.storeUser(HibernateJtracDao.java:247)<br>	at info.jtrac.JtracImpl.storeUser(JtracImpl.java:468)<br>	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:301)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)<br>	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)<br>	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)<br>	at com.sun.proxy.$Proxy1.storeUser(Unknown Source)<br>	at info.jtrac.JtracTest.testLogicToFindNotUsersAndSpacesNotAllocated(JtracTest.java:353)<br>	at org.springframework.test.ConditionalTestCase.runBare(ConditionalTestCase.java:76)<br>Caused by: org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)<br>	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:40)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2158)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2638)<br>	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:48)<br>	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:250)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:298)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)<br>	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)<br>	at org.hibernate.event.def.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:186)<br>	at org.springframework.orm.hibernate3.support.IdTransferringMergeEventListener.entityIsTransient(IdTransferringMergeEventListener.java:58)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:123)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)<br>	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)<br>	at org.springframework.orm.hibernate3.HibernateTemplate$23.doInHibernate(HibernateTemplate.java:772)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:373)<br>Caused by: java.sql.SQLException: Unique constraint violation: SYS_CT_66 in statement [insert into users (id, type, parent, login_name, name, password, email, locale, locked, metadata_id) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)]<br>	at org.hsqldb.jdbc.Util.throwError(Unknown Source)<br>	at org.hsqldb.jdbc.jdbcPreparedStatement.executeUpdate(Unknown Source)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:33)<br>
</code></td><td>0.027</td>
</tr>
<tr valign="top" class="Error">
<td><a href="info/jtrac/0_JtracTest.html">JtracTest</a></td><td><a name="testStoreAndLoadUserWithAdminRole"></a><a href="info/jtrac/0_JtracTest.html#testStoreAndLoadUserWithAdminRole">testStoreAndLoadUserWithAdminRole</a></td><td>Error</td><td>could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>
<br>
<code>org.springframework.dao.DataIntegrityViolationException: could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:622)<br>	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:378)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.merge(HibernateTemplate.java:769)<br>	at info.jtrac.hibernate.HibernateJtracDao.storeUser(HibernateJtracDao.java:247)<br>	at info.jtrac.JtracImpl.storeUser(JtracImpl.java:468)<br>	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:301)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)<br>	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)<br>	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)<br>	at com.sun.proxy.$Proxy1.storeUser(Unknown Source)<br>	at info.jtrac.JtracTest.testStoreAndLoadUserWithAdminRole(JtracTest.java:141)<br>	at org.springframework.test.ConditionalTestCase.runBare(ConditionalTestCase.java:76)<br>Caused by: org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)<br>	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:40)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2158)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2638)<br>	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:48)<br>	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:250)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:298)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)<br>	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)<br>	at org.hibernate.event.def.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:186)<br>	at org.springframework.orm.hibernate3.support.IdTransferringMergeEventListener.entityIsTransient(IdTransferringMergeEventListener.java:58)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:123)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)<br>	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)<br>	at org.springframework.orm.hibernate3.HibernateTemplate$23.doInHibernate(HibernateTemplate.java:772)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:373)<br>Caused by: java.sql.SQLException: Unique constraint violation: SYS_CT_66 in statement [insert into users (id, type, parent, login_name, name, password, email, locale, locked, metadata_id) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)]<br>	at org.hsqldb.jdbc.Util.throwError(Unknown Source)<br>	at org.hsqldb.jdbc.jdbcPreparedStatement.executeUpdate(Unknown Source)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:33)<br>
</code></td><td>0.003</td>
</tr>
<tr valign="top" class="Error">
<td><a href="info/jtrac/0_JtracTest.html">JtracTest</a></td><td><a name="testGetItemAsHtmlDoesNotThrowException"></a><a href="info/jtrac/0_JtracTest.html#testGetItemAsHtmlDoesNotThrowException">testGetItemAsHtmlDoesNotThrowException</a></td><td>Error</td><td>could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>
<br>
<code>org.springframework.dao.DataIntegrityViolationException: could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:622)<br>	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:378)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.merge(HibernateTemplate.java:769)<br>	at info.jtrac.hibernate.HibernateJtracDao.storeUser(HibernateJtracDao.java:247)<br>	at info.jtrac.JtracImpl.storeUser(JtracImpl.java:468)<br>	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:301)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)<br>	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)<br>	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)<br>	at com.sun.proxy.$Proxy1.storeUser(Unknown Source)<br>	at info.jtrac.JtracTest.testGetItemAsHtmlDoesNotThrowException(JtracTest.java:240)<br>	at org.springframework.test.ConditionalTestCase.runBare(ConditionalTestCase.java:76)<br>Caused by: org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)<br>	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:40)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2158)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2638)<br>	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:48)<br>	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:250)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:298)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)<br>	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)<br>	at org.hibernate.event.def.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:186)<br>	at org.springframework.orm.hibernate3.support.IdTransferringMergeEventListener.entityIsTransient(IdTransferringMergeEventListener.java:58)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:123)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)<br>	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)<br>	at org.springframework.orm.hibernate3.HibernateTemplate$23.doInHibernate(HibernateTemplate.java:772)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:373)<br>Caused by: java.sql.SQLException: Unique constraint violation: SYS_CT_66 in statement [insert into users (id, type, parent, login_name, name, password, email, locale, locked, metadata_id) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)]<br>	at org.hsqldb.jdbc.Util.throwError(Unknown Source)<br>	at org.hsqldb.jdbc.jdbcPreparedStatement.executeUpdate(Unknown Source)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:33)<br>
</code></td><td>0.023</td>
</tr>
<tr valign="top" class="Error">
<td><a href="info/jtrac/0_JtracTest.html">JtracTest</a></td><td><a name="testDeleteItemThatHasRelatedItems"></a><a href="info/jtrac/0_JtracTest.html#testDeleteItemThatHasRelatedItems">testDeleteItemThatHasRelatedItems</a></td><td>Error</td><td>could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>
<br>
<code>org.springframework.dao.DataIntegrityViolationException: could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:622)<br>	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:378)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.merge(HibernateTemplate.java:769)<br>	at info.jtrac.hibernate.HibernateJtracDao.storeUser(HibernateJtracDao.java:247)<br>	at info.jtrac.JtracImpl.storeUser(JtracImpl.java:468)<br>	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:301)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)<br>	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)<br>	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)<br>	at com.sun.proxy.$Proxy1.storeUser(Unknown Source)<br>	at info.jtrac.JtracTest.testDeleteItemThatHasRelatedItems(JtracTest.java:259)<br>	at org.springframework.test.ConditionalTestCase.runBare(ConditionalTestCase.java:76)<br>Caused by: org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)<br>	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:40)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2158)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2638)<br>	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:48)<br>	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:250)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:298)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)<br>	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)<br>	at org.hibernate.event.def.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:186)<br>	at org.springframework.orm.hibernate3.support.IdTransferringMergeEventListener.entityIsTransient(IdTransferringMergeEventListener.java:58)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:123)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)<br>	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)<br>	at org.springframework.orm.hibernate3.HibernateTemplate$23.doInHibernate(HibernateTemplate.java:772)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:373)<br>Caused by: java.sql.SQLException: Unique constraint violation: SYS_CT_66 in statement [insert into users (id, type, parent, login_name, name, password, email, locale, locked, metadata_id) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)]<br>	at org.hsqldb.jdbc.Util.throwError(Unknown Source)<br>	at org.hsqldb.jdbc.jdbcPreparedStatement.executeUpdate(Unknown Source)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:33)<br>
</code></td><td>0.017</td>
</tr>
<tr valign="top" class="Error">
<td><a href="info/jtrac/0_JtracTest.html">JtracTest</a></td><td><a name="testDeletingUserDeletesItemUsersAlso"></a><a href="info/jtrac/0_JtracTest.html#testDeletingUserDeletesItemUsersAlso">testDeletingUserDeletesItemUsersAlso</a></td><td>Error</td><td>could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>
<br>
<code>org.springframework.dao.DataIntegrityViolationException: could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:622)<br>	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:378)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.merge(HibernateTemplate.java:769)<br>	at info.jtrac.hibernate.HibernateJtracDao.storeUser(HibernateJtracDao.java:247)<br>	at info.jtrac.JtracImpl.storeUser(JtracImpl.java:468)<br>	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:301)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)<br>	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)<br>	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)<br>	at com.sun.proxy.$Proxy1.storeUser(Unknown Source)<br>	at info.jtrac.JtracTest.testDeletingUserDeletesItemUsersAlso(JtracTest.java:296)<br>	at org.springframework.test.ConditionalTestCase.runBare(ConditionalTestCase.java:76)<br>Caused by: org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)<br>	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:40)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2158)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2638)<br>	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:48)<br>	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:250)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:298)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)<br>	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)<br>	at org.hibernate.event.def.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:186)<br>	at org.springframework.orm.hibernate3.support.IdTransferringMergeEventListener.entityIsTransient(IdTransferringMergeEventListener.java:58)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:123)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)<br>	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)<br>	at org.springframework.orm.hibernate3.HibernateTemplate$23.doInHibernate(HibernateTemplate.java:772)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:373)<br>Caused by: java.sql.SQLException: Unique constraint violation: SYS_CT_66 in statement [insert into users (id, type, parent, login_name, name, password, email, locale, locked, metadata_id) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)]<br>	at org.hsqldb.jdbc.Util.throwError(Unknown Source)<br>	at org.hsqldb.jdbc.jdbcPreparedStatement.executeUpdate(Unknown Source)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:33)<br>
</code></td><td>0.012</td>
</tr>
<tr valign="top" class="Error">
<td><a href="info/jtrac/0_JtracTest.html">JtracTest</a></td><td><a name="testRenameSpaceRole"></a><a href="info/jtrac/0_JtracTest.html#testRenameSpaceRole">testRenameSpaceRole</a></td><td>Error</td><td>could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>
<br>
<code>org.springframework.dao.DataIntegrityViolationException: could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:622)<br>	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:378)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.merge(HibernateTemplate.java:769)<br>	at info.jtrac.hibernate.HibernateJtracDao.storeUser(HibernateJtracDao.java:247)<br>	at info.jtrac.JtracImpl.storeUser(JtracImpl.java:468)<br>	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:301)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)<br>	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)<br>	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)<br>	at com.sun.proxy.$Proxy1.storeUser(Unknown Source)<br>	at info.jtrac.JtracTest.testRenameSpaceRole(JtracTest.java:222)<br>	at org.springframework.test.ConditionalTestCase.runBare(ConditionalTestCase.java:76)<br>Caused by: org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)<br>	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:40)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2158)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2638)<br>	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:48)<br>	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:250)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:298)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)<br>	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)<br>	at org.hibernate.event.def.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:186)<br>	at org.springframework.orm.hibernate3.support.IdTransferringMergeEventListener.entityIsTransient(IdTransferringMergeEventListener.java:58)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:123)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)<br>	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)<br>	at org.springframework.orm.hibernate3.HibernateTemplate$23.doInHibernate(HibernateTemplate.java:772)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:373)<br>Caused by: java.sql.SQLException: Unique constraint violation: SYS_CT_66 in statement [insert into users (id, type, parent, login_name, name, password, email, locale, locked, metadata_id) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)]<br>	at org.hsqldb.jdbc.Util.throwError(Unknown Source)<br>	at org.hsqldb.jdbc.jdbcPreparedStatement.executeUpdate(Unknown Source)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:33)<br>
</code></td><td>0.008</td>
</tr>
<tr valign="top" class="Error">
<td><a href="info/jtrac/0_JtracTest.html">JtracTest</a></td><td><a name="testUserSpaceRolesInsert"></a><a href="info/jtrac/0_JtracTest.html#testUserSpaceRolesInsert">testUserSpaceRolesInsert</a></td><td>Error</td><td>could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>
<br>
<code>org.springframework.dao.DataIntegrityViolationException: could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:622)<br>	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:378)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.merge(HibernateTemplate.java:769)<br>	at info.jtrac.hibernate.HibernateJtracDao.storeUser(HibernateJtracDao.java:247)<br>	at info.jtrac.JtracImpl.storeUser(JtracImpl.java:468)<br>	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:301)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)<br>	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)<br>	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)<br>	at com.sun.proxy.$Proxy1.storeUser(Unknown Source)<br>	at info.jtrac.JtracTest.testUserSpaceRolesInsert(JtracTest.java:108)<br>	at org.springframework.test.ConditionalTestCase.runBare(ConditionalTestCase.java:76)<br>Caused by: org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)<br>	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:40)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2158)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2638)<br>	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:48)<br>	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:250)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:298)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)<br>	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)<br>	at org.hibernate.event.def.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:186)<br>	at org.springframework.orm.hibernate3.support.IdTransferringMergeEventListener.entityIsTransient(IdTransferringMergeEventListener.java:58)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:123)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)<br>	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)<br>	at org.springframework.orm.hibernate3.HibernateTemplate$23.doInHibernate(HibernateTemplate.java:772)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:373)<br>Caused by: java.sql.SQLException: Unique constraint violation: SYS_CT_66 in statement [insert into users (id, type, parent, login_name, name, password, email, locale, locked, metadata_id) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)]<br>	at org.hsqldb.jdbc.Util.throwError(Unknown Source)<br>	at org.hsqldb.jdbc.jdbcPreparedStatement.executeUpdate(Unknown Source)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:33)<br>
</code></td><td>0.008</td>
</tr>
<tr valign="top" class="Error">
<td><a href="info/jtrac/0_JtracTest.html">JtracTest</a></td><td><a name="testUserInsertAndLoad"></a><a href="info/jtrac/0_JtracTest.html#testUserInsertAndLoad">testUserInsertAndLoad</a></td><td>Error</td><td>could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>
<br>
<code>org.springframework.dao.DataIntegrityViolationException: could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:622)<br>	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:378)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.merge(HibernateTemplate.java:769)<br>	at info.jtrac.hibernate.HibernateJtracDao.storeUser(HibernateJtracDao.java:247)<br>	at info.jtrac.JtracImpl.storeUser(JtracImpl.java:468)<br>	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:301)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)<br>	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)<br>	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)<br>	at com.sun.proxy.$Proxy1.storeUser(Unknown Source)<br>	at info.jtrac.JtracTest.testUserInsertAndLoad(JtracTest.java:90)<br>	at org.springframework.test.ConditionalTestCase.runBare(ConditionalTestCase.java:76)<br>Caused by: org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)<br>	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:40)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2158)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2638)<br>	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:48)<br>	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:250)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:298)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)<br>	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)<br>	at org.hibernate.event.def.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:186)<br>	at org.springframework.orm.hibernate3.support.IdTransferringMergeEventListener.entityIsTransient(IdTransferringMergeEventListener.java:58)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:123)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)<br>	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)<br>	at org.springframework.orm.hibernate3.HibernateTemplate$23.doInHibernate(HibernateTemplate.java:772)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:373)<br>Caused by: java.sql.SQLException: Unique constraint violation: SYS_CT_66 in statement [insert into users (id, type, parent, login_name, name, password, email, locale, locked, metadata_id) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)]<br>	at org.hsqldb.jdbc.Util.throwError(Unknown Source)<br>	at org.hsqldb.jdbc.jdbcPreparedStatement.executeUpdate(Unknown Source)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:33)<br>
</code></td><td>0.003</td>
</tr>
<tr valign="top" class="Error">
<td><a href="info/jtrac/0_JtracTest.html">JtracTest</a></td><td><a name="testItemInsertAndCounts"></a><a href="info/jtrac/0_JtracTest.html#testItemInsertAndCounts">testItemInsertAndCounts</a></td><td>Error</td><td>could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>
<br>
<code>org.springframework.dao.DataIntegrityViolationException: could not insert: [info.jtrac.domain.User]; nested exception is org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:622)<br>	at org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:412)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:378)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.merge(HibernateTemplate.java:769)<br>	at info.jtrac.hibernate.HibernateJtracDao.storeUser(HibernateJtracDao.java:247)<br>	at info.jtrac.JtracImpl.storeUser(JtracImpl.java:468)<br>	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:301)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:182)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:149)<br>	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:106)<br>	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:171)<br>	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)<br>	at com.sun.proxy.$Proxy1.storeUser(Unknown Source)<br>	at info.jtrac.JtracTest.testItemInsertAndCounts(JtracTest.java:171)<br>	at org.springframework.test.ConditionalTestCase.runBare(ConditionalTestCase.java:76)<br>Caused by: org.hibernate.exception.ConstraintViolationException: could not insert: [info.jtrac.domain.User]<br>	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)<br>	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:40)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2158)<br>	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2638)<br>	at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:48)<br>	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:250)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:298)<br>	at org.hibernate.event.def.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:181)<br>	at org.hibernate.event.def.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:107)<br>	at org.hibernate.event.def.DefaultMergeEventListener.entityIsTransient(DefaultMergeEventListener.java:186)<br>	at org.springframework.orm.hibernate3.support.IdTransferringMergeEventListener.entityIsTransient(IdTransferringMergeEventListener.java:58)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:123)<br>	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:53)<br>	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:677)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:661)<br>	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:665)<br>	at org.springframework.orm.hibernate3.HibernateTemplate$23.doInHibernate(HibernateTemplate.java:772)<br>	at org.springframework.orm.hibernate3.HibernateTemplate.execute(HibernateTemplate.java:373)<br>Caused by: java.sql.SQLException: Unique constraint violation: SYS_CT_66 in statement [insert into users (id, type, parent, login_name, name, password, email, locale, locked, metadata_id) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?)]<br>	at org.hsqldb.jdbc.Util.throwError(Unknown Source)<br>	at org.hsqldb.jdbc.jdbcPreparedStatement.executeUpdate(Unknown Source)<br>	at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:33)<br>
</code></td><td>0.007</td>
</tr>
</table>
</body>
</html>
